Repository rticommunity/rticonnextdds-examples, pull requests merged in 2019-11, with the labels that each got.

#254 Fixing wrong clang-format executable name in travis format script
  resources/travis/linux_format.py
Labels: bug

#268 Feature/record 1120
  examples/recording_service/pluggable_storage/c/CMakeLists.txt
  examples/recording_service/pluggable_storage/c/README.md
  examples/recording_service/pluggable_storage/cpp/CMakeLists.txt
  examples/recording_service/pluggable_storage/cpp/README.md
  examples/recording_service/service_as_lib/cpp/CMakeLists.txt
  examples/recording_service/service_as_lib/cpp/README.md
Labels: build, documentation

#271 Feature/record 1119
  examples/recording_service/pluggable_storage/c/README.md
  examples/recording_service/pluggable_storage/cpp/README.md
  examples/recording_service/service_admin/cpp/README.md
  examples/recording_service/service_as_lib/cpp/README.md
Labels: build

#270 Feature/record 1121
  examples/recording_service/service_admin/cpp/Requester.cxx
  examples/recording_service/service_admin/cpp/Requester.hpp
Labels: bug
