Repository rticommunity/rticonnextdds-examples, pull requests merged in 2019-09, with the labels that each got.

#236 Fix markdown lint
  .travis.yml
  examples/connext_dds/flat_data_api/c++98/README.md
Labels: documentation

#235 Fix clang-format-version
  .travis.yml
  resources/travis/linux_format.py
Labels: bug, build

#231 #229: Added missing libraries and their documentation.
  .travis.yml
  resources/cmake/FindRTIConnextDDS.cmake
Labels: build, documentation

#230 #228: Added flag to compile against imported targets debug mode
  examples/connext_dds/flat_data_api/c++98/CameraImage_publisher.cxx
  examples/connext_dds/flat_data_api/c++98/CameraImage_subscriber.cxx
  examples/connext_dds/flat_data_api/c++98/README.md
  examples/connext_dds/flat_data_latency/c++11/Common.hpp
  examples/recording_service/pluggable_storage/c/CMakeLists.txt
  examples/recording_service/pluggable_storage/cpp/CMakeLists.txt
  examples/routing_service/routing_service_shapes_processor/cpp/CMakeLists.txt
  examples/routing_service/routing_service_struct_array_transf/cpp/CMakeLists.txt
  resources/cmake/FindRTIConnextDDS.cmake
Labels: build

#233 #232: Add login to find_package
  resources/cmake/FindRTIConnextDDS.cmake
Labels: build, enhancement
