Repository rticommunity/rticonnextdds-examples, pull requests merged in 2019-05, with the labels that each got.

#197 Fixed make searching in path libraries instead of in RTICONNEXTDDS_DIR directory
  resources/cmake/FindRTIConnextDDS.cmake
Labels: bug, build

#195 Added python script to upload rti_connextdds code to amazon bucket.
  .gitignore
  examples/routing_service/routing_service_shapes_processor/cpp/.gitignore
  examples/routing_service/routing_service_struct_array_transf/.gitignore
  resources/aws/requirements.txt
  resources/aws/rti_aws_uploader.py
Labels: enhancement

#204 Update example/recording service recording partitions in groups
  examples/recording_service_recording_partitions_in_groups/README.md
  examples/recording_service_recording_partitions_in_groups/RecordingServiceLauncher.png
  examples/recording_service_recording_partitions_in_groups/ReplayServiceLauncher.png
  examples/recording_service_recording_partitions_in_groups/config_record.xml
  examples/recording_service_recording_partitions_in_groups/config_replay.xml
Labels: documentation, enhancement

#206 Added script to build all the configurations
  examples/connext_dds/build_systems/cmake/CMakeLists.txt
  resources/cmake/ConnextDdsBuildAllConfigurations.cmake
Labels: build, enhancement, good first issue

#202 Git hooks and continuous integration
  .markdownlint.json
  .travis.yml
  CONTRIBUTING.md
  githooks/README.md
  githooks/pre-commit
Labels: enhancement, good first issue, style
